### ISSUE TITLE
Tags is not expected here

### ISSUE THREAD

**Issue by jimsmith** [trussworks/terraform-aws-vpc-flow-logs#11]
Issue:

    Error: Unsupported argument
      on vpc.tf line 37, in module "vpc_flow_logs":
      37:   tags           = module.aws_tags.tags
    An argument named "tags" is not expected here.

    module "vpc_flow_logs" {
      source         = "trussworks/vpc-flow-logs/aws"
      version        = "2.2.0"
      vpc_name       = var.vpc_name
      vpc_id         = module.aws-vpc.vpc_id
      tags           = module.aws_tags.tags
    }

Can you please fix this as it's stopping this module from being used as tags is not supported.

I can see there has been some work done in `main` branch but not all resources that support `tags` has such as IAM role itself.

**Comment by avanti-joshi** [comment]
@jimsmith I've created a release with the latest changes that added tagging functionality here: https://github.com/trussworks/terraform-aws-vpc-flow-logs/releases/tag/v2.3.0 - thank you!
